VERSION 0.8

all: 
    BUILD ../base+rust-builder
    BUILD ../base+reth

    BUILD +unit-test
    BUILD +state-test
    BUILD +doc-test

# most run test
unit-test:
    FROM ../base+reth
    RUN echo "unit-test"
    # RUN cargo nextest run --workspace --locked --exclude examples --exclude ef-tests

# slow test
state-test:
    FROM ../base+reth
    GIT CLONE https://github.com/ethereum/tests reth/testing/ef-tests/ethereum-tests
    WORKDIR reth/ef-tests/ethereum-tests
    RUN echo "state-test"
    # RUN cargo nextest run --release -p ef-tests --features "asm-keccak ef-tests"

doc-test:
    FROM ../base+reth
    GIT CLONE https://github.com/paradigmxyz/reth reth
    RUN echo "doc-test"
    # RUN cargo test --doc

# release management
